<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Registered Vendors Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #334155; margin: 0; padding: 20px; line-height: 1.5; }
        
        /* Page Styling */
        .page {
            page-break-after: always;
            position: relative;
        }
        .page:last-child {
            page-break-after: auto;
        }

        /* Header */
        .header { display: table; width: 100%; border-bottom: 3px solid #bd2427; padding-bottom: 15px; margin-bottom: 25px; }
        .header-left { display: table-cell; vertical-align: bottom; }
        .header-right { display: table-cell; text-align: right; vertical-align: bottom; font-size: 10px; color: #64748b; }
        .brand { font-weight: 900; font-size: 22px; color: #bd2427; letter-spacing: -0.5px; text-transform: uppercase; margin-bottom: 4px; }
        .store-name { margin: 0 0 2px 0; color: #0f172a; font-size: 18px; font-weight: 700; text-transform: uppercase; }
        .report-title { margin: 0; color: #64748b; font-size: 11px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.5px; }
        
        /* Data Table */
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .data-table th, .data-table td { padding: 10px 8px; border-bottom: 1px solid #e2e8f0; text-align: left; vertical-align: middle; }
        .data-table th { background-color: #3f0909; color: #f8fafc; font-weight: 700; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #bd2427; }
        .data-table tbody tr:nth-child(even) { background-color: #f8fafc; }
        .data-table td { font-size: 10px; color: #1e293b; }
        
        /* Badges */
        .badge { padding: 3px 8px; border-radius: 4px; font-size: 8px; font-weight: 800; text-transform: uppercase; display: inline-block; line-height: 1; }
        .badge-active { background: #dcfce7; color: #166534; border: 1px solid #bbf7d0; }
        .badge-deleted { background: #fee2e2; color: #991b1b; border: 1px solid #fecaca; }
        .badge-suspended { background: #fef08a; color: #854d0e; border: 1px solid #fde047; }
        
        .page-number:before { content: "Page " counter(page); }
        
        /* PDF Footer fixed at bottom of every page */
        footer {
            position: fixed; 
            bottom: -20px; 
            left: 0px; 
            right: 0px;
            height: 30px; 
            font-size: 9px; 
            color: #94a3b8; 
            border-top: 1px solid #e2e8f0; 
            padding-top: 8px;
        }
    </style>
</head>
<body>

<footer>
    <table style="width: 100%; border: none;">
        <tr>
            <td style="text-align: left; border: none; padding: 0;">Generated by Tindahan E-Commerce | DTI NEGOSYO CENTER NCR: MANDALUYONG CITY - LGU</td>
            <td style="text-align: right; border: none; padding: 0;">
                <span class="page-number"></span>
            </td>
        </tr>
    </table>
</footer>

<div class="header">
    <div class="header-left">
        <div class="brand">Tindahan E-Commerce</div>
        <h1 class="store-name">DTI NEGOSYO CENTER NCR: MANDALUYONG CITY - LGU</h1>
        <h3 class="report-title">Registered Vendors Report</h3>
    </div>
    <div class="header-right">
        Generated on: <strong>{{ $date }}</strong><br>
        Generated by:<br>
        <strong>{{ $admin->full_name ?? 'Administrator' }}</strong><br>
        Administrator &mdash; DTI NEGOSYO CENTER NCR: MANDALUYONG CITY - LGU
    </div>
</div>

<table class="data-table">
    <thead>
        <tr>
            <th>Vendor Name</th>
            <th>Store Name</th>
            <th>Email & Phone</th>
            <th>Address</th>
            <th>Status</th>
            <th>Joined Date</th>
        </tr>
    </thead>
    <tbody>
        @forelse($vendors as $vendor)
            @php
                $store = $vendor->store;
                $isDeleted = $vendor->trashed();
                if ($isDeleted) {
                    $status = 'deleted';
                    $badgeClass = 'badge-deleted';
                } else {
                    $status = strtolower($vendor->user_status ?? 'active');
                    $badgeClass = $status === 'active' ? 'badge-active' : 'badge-suspended';
                }
                
                $statusBadge = '<span class="badge ' . $badgeClass . '">' . ucfirst($status) . '</span>';
            @endphp
            
            <tr>
                <td><strong>{{ $vendor->full_name ?? 'N/A' }}</strong></td>
                <td><strong>{{ $store->store_name ?? 'N/A' }}</strong></td>
                <td>
                    <span style="color: #64748b; font-size: 9px;">{{ $vendor->email ?? 'N/A' }}</span><br>
                    <span style="color: #64748b; font-size: 9px;">{{ $vendor->phone_number ?? 'N/A' }}</span>
                </td>
                <td style="max-width: 150px; line-height: 1.3;">{{ $store->address ?? 'N/A' }}</td>
                <td>{!! $statusBadge !!}</td>
                <td>{{ $vendor->created_at ? \Carbon\Carbon::parse($vendor->created_at)->format('Y-m-d') : 'N/A' }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="6" style="text-align: center; padding: 30px; color: #64748b; font-style: italic;">
                    No registered vendors found.
                </td>
            </tr>
        @endforelse
    </tbody>
</table>

</body>
</html>
